### ISSUE TITLE
Invisible antirush zones

### ISSUE THREAD

**Issue by sebastiansuciu** [oscar-wos/AntiRush#4]
Hello,

Great work with the plugin! Very easy to use and set but I don't know if there is a problem on my end but the walls/zones are invisible and the players would not know where should they stop. (the walls/zones are working like they bounce or kill you, but you can't see anything)

I would like to know if this is a problem on my end or the zones aren't displayed at all. If that's the case, would be great to have a visual graphic in game like some red lines between the points of the zone.

EDIT: would be great to see in the next feature a timer which deactivates the antirush zones in the current round, like after 30 seconds (a variable would be cool to change after how many seconds the zones are removed), because as I tested the zones are there forever now.

Thank you.

**Comment by oscar-wos** [comment]
`configs/plugins/AntiRush/AntiRush.json`
```json
  "DrawZones": false,
  "NoRushTime": 0,
  "NoCampTime": 0,
  ```
  
  https://github.com/oscar-wos/AntiRush/actions/runs/9756739897/artifacts/1658454305
  
  Let me know if there are any problems

**Comment by sebastiansuciu** [comment]
Hello,

It doesn't help because the plugin doesn't generate the config file, AntiRush.json, it creates only map names json files like de_dust2.json, de_inferno.json etc. 

I have tried to create the AntiRush json and put in config file of the plugin but doesn't help at all because the plugin probably doesn't read it.

Thank you for answer.

**Comment by oscar-wos** [comment]
Can you confirm you are using the latest build, not the latest "release" as i have not merged into main
![librewolf_TgQcDnynmg](https://github.com/oscar-wos/AntiRush/assets/29248751/15511bcb-3f27-4f7e-b32f-c7ab9dca784a)

**Comment by oscar-wos** [comment]
https://github.com/oscar-wos/AntiRush/actions/runs/9756838747

**Comment by sebastiansuciu** [comment]
Thank you, I have downloaded it, it generates the config file but it fails loading.

![image](https://github.com/oscar-wos/AntiRush/assets/38329524/0bb7d3a5-07f5-4803-a559-c1ce007250ad)

**Comment by oscar-wos** [comment]
okay this should fix it:
https://github.com/oscar-wos/AntiRush/actions/runs/9763684677

**Comment by sebastiansuciu** [comment]
Yup is working fine now. Thanks. Would be awesome to have a setting to disable it while warmup round is on.

Thank you again for help.

**Comment by oscar-wos** [comment]
https://github.com/oscar-wos/AntiRush/actions/runs/9785545183/artifacts/1665889097

```
// This configuration was automatically generated by CounterStrikeSharp for plugin 'AntiRush', at 2024/07/03 08:56:24
{
  "Version": 3,
  "Messages": "simple", // "simple", "detailed", "off"
  "DrawZones": false,
  "Warmup": true, // Do zones in warmup
  "NoRushTime": 0,
  "NoCampTime": 0,
  "ConfigVersion": 3
}
```
