### ISSUE TITLE
antirush zones doesn't disabled after certain time

### ISSUE THREAD

**Issue by sebastiansuciu** [oscar-wos/AntiRush#6]
Hello,

I have configured to expire after X seconds, I use detailed message and in chat the timer is counting down until it say "Antirush disabled" and when I try to pass trough a zone, I die (because I set it to kill).

Also would be great/better just to remove the zones after the specific time is met (or bomb planted). This way would be less confusing for new players.

P.S. I have tried the latest plugin but also a lot of commits from 1.0.3 when you introduced messages, I have tried almost all commits 1 by 1 and nothing worked.

Thank you,
Sebastian.

**Comment by oscar-wos** [comment]
https://github.com/oscar-wos/AntiRush/commit/7d251dc907e4c60be50a4d6dfe1a3c3ce161b3f7

Delete your config to regenerate new file

```json
{
  "CampZones": [ 1 ],    // 0 - Bounce, 1 - Hurt, 2 - Kill, 3 - Teleport
}
```
